In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('Datasets/BL-Flickr-Images-Book.csv')

df.head()

to_drop = ['Edition Statement',
           'Corporate Author',
           'Corporate Contributors',
           'Former owner',
           'Engraver',
           'Contributors',
           'Issuance type',
           'Shelfmarks']

df.drop(to_drop, inplace=True, axis=1)

In [2]:
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [4]:
df['Identifier'].is_unique

True

In [6]:
df = df.set_index('Identifier')

In [7]:
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [19]:
df.loc[206]

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [13]:
df.iloc[1:3]

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...

In [22]:
df.get_dtype_counts()

object    6
dtype: int64

In [27]:
df.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

In [28]:
regex = r'^(\d{4})'

In [30]:
extr = df['Date of Publication'].str.extract(r'^(\d{4})', expand=False)

In [31]:
extr.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [32]:
df

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
874,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1808,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
1905,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
1929,Amsterdam,"1839, 38-54",NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2836,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
2854,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
2956,Paris,1860-63,NaN,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
2957,Paris,1873,NaN,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
3017,Puerto-Rico,1866,NaN,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
3131,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
4598,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
4884,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4976,Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
5382,London,"1847, 48 [1846-48]",Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5385,London,[1897?],"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5389,London,[1897?],"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5432,Milano,1893,NaN,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
6036,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
6821,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
7521,Wien,1896,NaN,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
4053464,"London: E. Nutt; E. Cooke, 1733",NaN,NaN,A friendly epistle [by Joseph Mitchell?] to th...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4063671,London,1896,Richard Bentley & Son,Honor Ormthwaite. By the author of “Lady Jean'...,"KEDDIE, Henrietta.",http://www.flickr.com/photos/britishlibrary/ta...
4072044,"London: D. Wilson & T. Durham, 1752",NaN,NaN,"The scale: or, Woman weighed with man. A poem ...","MONCREIFF, John.",http://www.flickr.com/photos/britishlibrary/ta...
4077038,"London: printed for Nicholas Vavasour, 1634",NaN,NaN,"The noble souldier. Or, A contract broken, jus...","ROWLEY, Samuel - Dramatist",http://www.flickr.com/photos/britishlibrary/ta...
4079258,Glasgow,1750,"printed for John Ross, bookseller in Edinburgh",[Yarico to Inkle.] The epistle of Yarico to In...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4079262,London,1879,NaN,The Canadian farmer. A missionary incident. [S...,"YATES, William Joseph H.",http://www.flickr.com/photos/britishlibrary/ta...
4112297,"London: Macmillan & Co., pp. xl, 400. 1895",NaN,NaN,Japhet in search of a Father ... With an intro...,"Marryat, Frederick",http://www.flickr.com/photos/britishlibrary/ta...
4112525,Pontoise,1889,NaN,Histoire populaire de Pontoise ... Précédée...,"DEPOIN, Joseph.",http://www.flickr.com/photos/britishlibrary/ta...
4112839,London,[1845.],Willoughby & Co.,The Vicar of Wakefield ... And a prefatory mem...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
4113012,Philadelphia,1876,S. W. Burley,1776 American Enterprise. 1876. Burley's Unite...,"KIDDER, Charles Holland.|Pope, Alexander",http://www.flickr.com/photos/britishlibrary/ta...
4113816,"pp. xxvi, 375. London: Jackson, Walford & Hodd...",NaN,NaN,The lacemakers: sketches of Irish characters w...,"MEREDITH, Susanna.|WIBERG, Carl Fredrik.",http://www.flickr.com/photos/britishlibrary/ta...
4114334,"pp. viii. 64. J. Debrett: London, 1789",NaN,NaN,"The Sword of Peace; or, a voyage of love; a co...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4114390,London,1708,NaN,"THe Unfortunate Dutchess of Malfy, or, The Unn...","WEBSTER, John - Dramatist|SCOTT, Michael - of ...",http://www.flickr.com/photos/britishlibrary/ta...
4114889,London,[1868],NaN,"The 5 Alls. A collection of stories, charades,...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4114986,London,1777,J. Wenman,[Barbarossa. A tragedy. As it is performed at ...,"BROWN, John - Vicar of Newcastle-upon-Tyne",http://www.flickr.com/photos/britishlibrary/ta...
4115138,"G. Eld: London, 1608",NaN,NaN,The Revenger's Tagaedie. As it hath beene sund...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4116063,London,1866,[John Dicks],"Edith Heron; or, the Earl and the countess. [B...","HERON, Edith.",http://www.flickr.com/photos/britishlibrary/ta...
4117526,Leipzig,1862,Charles Fr. Fleischer,Abridgment of the History of England ... Adapt...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
4117583,London,1894,T. Fisher Unwin,The Wish. A novel by Hermann Sudermann. Transl...,"SUDERMANN, Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
4117749,New York,1868,John Wiley & Son,A System of Mineralogy. Descriptive Mineralogy...,"DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4117751,New York,1882,John Wiley & Sons,Third Appendix to the fifth edition of Dana's ...,"DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4117752,London,"1883, [1884]",Trübner & Co.,"A System of Mineralogy ... Fifth edition, rewr...","DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4156359,New York,1898-1912,G. P. Putnam's Sons,History of the People of the Netherlands ... T...,"BLOK, Pieter Johan.",http://www.flickr.com/photos/britishlibrary/ta...
4157746,London,1811,F. C. and J. Rivington,"The New Chronicles of England and France, in t...","FABYAN, Robert.",http://www.flickr.com/photos/britishlibrary/ta...
4157862,Newcastle-upon-Tyne,1867,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne",http://www.flickr.com/photos/britishlibrary/ta...
4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [33]:
df['Place of Publication'].head(10)

Identifier
206                                  London
216                London; Virtue & Yorston
218                                  London
472                                  London
480                                  London
481                                  London
519                                  London
667     pp. 40. G. Bryan & Co: Oxford, 1898
874                                 London]
1143                                 London
Name: Place of Publication, dtype: object

In [37]:
pub = df['Place of Publication']
london = pub.str.contains('London')
london[0:5]

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [38]:
oxford = pub.str.contains('Oxford')

In [39]:
df['Place of Publication'] = np.where(london, 'London', np.where(oxford, 'Oxford', pub.str.replace('-', '')))

In [43]:
df['Place of Publication'].head(100)

Identifier
206                London
216                London
218                London
472                London
480                London
481                London
519                London
667                Oxford
874                London
1143               London
1280             Coventry
1808          Christiania
1905              Firenze
1929            Amsterdam
2836               Savona
2854               London
2956                Paris
2957                Paris
3017           PuertoRico
3131             New York
4598                 Hull
4884               London
4976               Oxonii
5382               London
5385               London
5389               London
5432               Milano
6036               London
6821             Aberdeen
7521                 Wien
               ...
29031              London
29032              London
29285              London
29505           A. Millar
29844            New York
30269          Allahabad]
31858              London
32896           Stuttgart
33745              London
33833    D. Appleton & Co
33881              London
34361     Санктпетербургъ
34463              London
34538             Paisley
34785              London
34793              London
34810              London
34826              London
34852              London
34914              London
34952              London
34967              London
34987              London
36171               Paris
36231              London
36521           Edinburgh
36531              Napoli
36721              London
38673        Ἐν Κερκυρᾳ
38986              London
Name: Place of Publication, Length: 100, dtype: object

In [44]:
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [45]:
data = pd.read_csv('university_towns.txt', sep=" ", header=None)

FileNotFoundError: [Errno 2] File b'university_towns.txt' does not exist: b'university_towns.txt'